version: "3"

services:
    logstash-filebeat: # ENRUTAMIENTO
        container_name: mi-logstash-filebeat
        image:          docker.elastic.co/logstash/logstash:8.13.2
        volumes:
                      - ./conf/pipeline-routing.conf:/usr/share/logstash/pipeline/logstash.conf
                      - /home/ubuntu/environment/datos/certificados/ca:/usr/share/logstash/certs/ca
        environment:
          xpack.monitoring.enabled: "true"
          xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/certs/ca/ca.crt"
          xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
          xpack.monitoring.elasticsearch.hosts: "https://coordinator1:9200"
          xpack.monitoring.elasticsearch.username: "elastic"
          xpack.monitoring.elasticsearch.password: "password"
        networks:
          - red-es

    logstash-negocio: # Lo puedo usar como fqdn en red
        container_name: mi-logstash-negocio
        image:          docker.elastic.co/logstash/logstash:8.13.2
        volumes:
                      - ./conf/pipeline-negocio.conf:/usr/share/logstash/pipeline/logstash.conf
                      - ./index_templates:/tmp/index_templates
                      - /home/ubuntu/environment/datos/certificados/ca:/usr/share/logstash/certs/ca
        environment:
          xpack.monitoring.enabled: "true"
          xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/certs/ca/ca.crt"
          xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
          xpack.monitoring.elasticsearch.hosts: "https://coordinator1:9200"
          xpack.monitoring.elasticsearch.username: "elastic"
          xpack.monitoring.elasticsearch.password: "password"
        networks:
          - red-es

    logstash-sistemas: # Lo puedo usar como fqdn en red
        container_name: mi-logstash-sistemas
        image:          docker.elastic.co/logstash/logstash:8.13.2
        volumes:
                      - ./conf/pipeline-sistemas.conf:/usr/share/logstash/pipeline/logstash.conf
                      - ./index_templates:/tmp/index_templates
                      - /home/ubuntu/environment/datos/certificados/ca:/usr/share/logstash/certs/ca
        environment:
          xpack.monitoring.enabled: "true"
          xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/certs/ca/ca.crt"
          xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
          xpack.monitoring.elasticsearch.hosts: "https://coordinator1:9200"
          xpack.monitoring.elasticsearch.username: "elastic"
          xpack.monitoring.elasticsearch.password: "password"
        networks:
          - red-es
  
  networks:
    red-es:
      name: elastic
      external: true # Ya existe... no la gestionamos desde este fichero