version: "3"

services:
    apache:
        container_name: mi-apache
        image:          httpd:latest
        ports:
                      - 8082:80
        volumes:
                      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
                      - /home/ubuntu/environment/datos/apache/log:/usr/local/apache2/logs
        networks:
          - red-es

    filebeat:
        container_name: mi-filebeat
        image:          docker.elastic.co/beats/filebeat:8.13.2
        volumes:
                      - /home/ubuntu/environment/datos/apache/log:/tmp/logs
                      - ./filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
        networks:
          - red-es

networks:
  red-es:
    name: elastic
    external: true # Ya existe... no la gestionamos desde este fichero