version: "3"

services:
    apache:
        container_name: mi-apache
        image:          httpd:latest
        ports:
                      - 8082:80
        volumes:
                      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
                      - /home/ubuntu/environment/datos/apache/log:/usr/local/apache2/logs
        networks:
          - red-es

networks:
  red-es:
    name: elastic
    external: true # Ya existe... no la gestionamos desde este fichero